# Generated by Django 4.2.30 on 2026-05-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(default="树洞主人", max_length=32)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("bio", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
