# Generated by Django 4.2.30 on 2026-05-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_siteprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="douyin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="phone_num",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="wechat_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
