# Generated by Django 4.2.30 on 2026-05-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_siteprofile_douyin_url_siteprofile_phone_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="admin_reply",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_unread",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
