# Generated by Django 4.2.30 on 2026-05-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_comment_admin_reply_comment_is_unread_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
