# Generated by Django 4.2.30 on 2026-05-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="email",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
