# Generated by Django 4.2.30 on 2026-05-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_siteprofile_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="timeline/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("shot_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-shot_at"],
            },
        ),
    ]
