# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_post_is_pinned_comment_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("artist", models.CharField(blank=True, default="未知艺术家", max_length=64)),
                ("file", models.FileField(upload_to="music/")),
                ("duration", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
