# Generated by Django 4.2.30 on 2026-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_postmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="session_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
