# Generated by Django 4.2.30 on 2026-05-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_siteprofile_session_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
