# Generated by Django 4.2.30 on 2026-05-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_blocked_keyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=512)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["path"], name="posts_pagev_path_541ea5_idx"),
                    models.Index(
                        fields=["created_at"], name="posts_pagev_created_cb3085_idx"
                    ),
                ],
            },
        ),
    ]
