# Generated by Django 4.2.30 on 2026-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_pageview"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
