# Generated by Django 4.2.30 on 2026-05-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_siteannouncement_updated_at_announcementmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ContentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[("comment", "Comment"), ("message", "Message")],
                        max_length=10,
                    ),
                ),
                ("source_id", models.PositiveIntegerField()),
                ("nickname", models.CharField(blank=True, max_length=32)),
                ("content", models.TextField()),
                ("ai_reason", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="posts_conte_status_c91792_idx"
                    ),
                    models.Index(
                        fields=["review_type", "source_id"],
                        name="posts_conte_review__f81ee5_idx",
                    ),
                ],
            },
        ),
    ]
