# Generated by Django 4.2.30 on 2026-05-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0017_comment_review_status_message_review_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageView",
        ),
    ]
