from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    AdminCommentMarkReadAPIView,
    AdminCommentReplyAPIView,
    AdminLoginView,
    AdminUnreadCommentCountAPIView,
    AdminUnreadCommentListAPIView,
    AIChatView,
    BlockedKeywordDestroyView,
    BlockedKeywordListCreateView,
    CommentDestroyAPIView,
    CommentListCreateAPIView,
    ContentReviewApproveAPIView,
    ContentReviewCountAPIView,
    ContentReviewListAPIView,
    ContentReviewRejectAPIView,
    MessageDestroyAPIView,
    MessageListCreateAPIView,
    MusicDestroyAPIView,
    MusicListAPIView,
    PostMediaDestroyView,
    PostViewSet,
    SiteAnnouncementDestroyView,
    SiteAnnouncementListCreateView,
    SiteAnnouncementPublicView,
    SiteAnnouncementUpdateView,
    SiteProfileAdminAPIView,
    SiteProfilePublicAPIView,
    TimelineMediaDestroyView,
    TimelineMediaDetailView,
    TimelineMediaListCreateView,
)

router = DefaultRouter()
router.register(r"posts", PostViewSet, basename="posts")

urlpatterns = [
    path("", include(router.urls)),
    path("profile/", SiteProfilePublicAPIView.as_view(), name="site-profile-public"),
    path(
        "admin/profile/",
        SiteProfileAdminAPIView.as_view(),
        name="site-profile-admin",
    ),
    path(
        "posts/<int:post_id>/comments/",
        CommentListCreateAPIView.as_view(),
        name="post-comments",
    ),
    path("comments/<int:pk>/", CommentDestroyAPIView.as_view(), name="comment-delete"),
    path("posts/<int:post_id>/media/<int:pk>/", PostMediaDestroyView.as_view(), name="post-media-delete"),
    path(
        "admin/comments/unread/count/",
        AdminUnreadCommentCountAPIView.as_view(),
        name="admin-unread-comment-count",
    ),
    path(
        "admin/comments/unread/",
        AdminUnreadCommentListAPIView.as_view(),
        name="admin-unread-comment-list",
    ),
    path(
        "admin/comments/<int:pk>/reply/",
        AdminCommentReplyAPIView.as_view(),
        name="admin-comment-reply",
    ),
    path("admin/comments/<int:pk>/read/",
        AdminCommentMarkReadAPIView.as_view(),
        name="admin-comment-read",
    ),
    path("admin/login/", AdminLoginView.as_view(), name="admin-login"),
    path("admin/keywords/", BlockedKeywordListCreateView.as_view(), name="admin-keyword-list"),
    path("admin/keywords/<int:pk>/", BlockedKeywordDestroyView.as_view(), name="admin-keyword-delete"),
    path("chat/", AIChatView.as_view(), name="ai-chat"),
    path("music/", MusicListAPIView.as_view(), name="music-list"),
    path("music/<int:pk>/", MusicDestroyAPIView.as_view(), name="music-delete"),
    path("messages/", MessageListCreateAPIView.as_view(), name="message-list"),
    path("messages/<int:pk>/", MessageDestroyAPIView.as_view(), name="message-delete"),
    path(
        "timeline/",
        TimelineMediaListCreateView.as_view(),
        name="timeline-media-list",
    ),
    path(
        "timeline/<int:pk>/",
        TimelineMediaDestroyView.as_view(),
        name="timeline-media-delete",
    ),
    path(
        "timeline/<int:pk>/edit/",
        TimelineMediaDetailView.as_view(),
        name="timeline-media-edit",
    ),
    path("announcements/", SiteAnnouncementPublicView.as_view(), name="announcement-public"),
    path("admin/announcements/", SiteAnnouncementListCreateView.as_view(), name="announcement-admin-list"),
    path("admin/announcements/<int:pk>/", SiteAnnouncementUpdateView.as_view(), name="announcement-admin-update"),
    path("admin/announcements/<int:pk>/delete/", SiteAnnouncementDestroyView.as_view(), name="announcement-admin-delete"),
    path("admin/reviews/", ContentReviewListAPIView.as_view(), name="admin-review-list"),
    path("admin/reviews/count/", ContentReviewCountAPIView.as_view(), name="admin-review-count"),
    path("admin/reviews/<int:pk>/approve/", ContentReviewApproveAPIView.as_view(), name="admin-review-approve"),
    path("admin/reviews/<int:pk>/reject/", ContentReviewRejectAPIView.as_view(), name="admin-review-reject"),
]
